version: '3'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PRISMA_MIGRATION_NAME=${PRISMA_MIGRATION_NAME}
    networks:
      - default-network
  node-app-migrate:
    container_name: node-app-migrate
    build:
      context: .
      dockerfile: ./apps/consumer/migrate.Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - default-network
    command: ./wait-for.sh postgres:5432 -- npx prisma migrate dev --name ${PRISMA_MIGRATION_NAME} # npx prisma migrate reset --force  # npx prisma db push
    volumes:
      - .:/app
      - node_modules:/app/node_modules
volumes:
  db_data:
  node_modules:
networks:
  default-network: